### ISSUE TITLE
Unable to hack a door without configuring the exception list first

### ISSUE THREAD

**Issue by Guthen** [Augaton/scp-hacking-device-reloaded#2]
When I was first testing the addon, I spent 10 minutes trying to understand why the hack was not working. By reading the code, I realised it was because no exception list was configured, so I ran the console command to unblock a button, which wrote an empty configuration file and fixed the issue. In my opinion, this is pretty annoying since it made me think the mod had a bug, and not that I was doing something wrong.

The [code](https://github.com/Augaton/scp-hacking-device-reloaded/blob/main/lua/weapons/weapon_hdevice/shared.lua#L131-L132) responsible for this is here:
```lua
if not hdevicereloaded.exceptionButtonID then return end -- No buttons file
if not hdevicereloaded.exceptionButtonID[game.GetMap()] then return end -- No setting for that map
```

Personally, (and from what I know of the mod) I think it should not be required to configure the exception list in order to be able to hack, therefore, I suggest to do one of these things:
+ Initialize the `hdevicereloaded.exceptionButtonID[game.GetMap()]` table to an empty table during `MODULE:init`, probably the best option
+ Adapt the code to not require the exception button ID table
+ Throw an error message to let people know that they have to configure the exception list first

**Comment by Augaton** [comment]
just a missing things i do in my server.lua, i just forgot to add hdevicereloaded. at the begining of exceptionButtonID[game.GetMap()]
