### ISSUE TITLE
Convert the old version detection for the actual mod's legacy version instead of `guthscpkeycard`'s legacy version

### ISSUE THREAD

**Issue by Guthen** [Augaton/scp-hacking-device-reloaded#4]
If this [code](https://github.com/Augaton/scp-hacking-device-reloaded/blob/main/lua/guthscp/modules/hdevicereloaded/main.lua#L135-L142) is intended, I think it would make more sense to check for [zgredinzyyy](https://github.com/zgredinzyyy/SCP-SWEP-HDevice)'s version instead of the old `guthscpkeycard` version since the remaster already does that.

Just as a guess, the way to do that would probably be checking for either:
+ the hook `PlayerInitialSpawn` using `hook.GetTable()["PlayerInitialSpawn"]["HDevice:GetIDs"]` (check first that the hooks table of `PlayerInitialSpawn` exists because it's not certain, plus clientside this hook isn't supposed to exist)
+ or the autorun file `lua/autorun/autorun_hdevice.lua` using `file.Exists`

**Comment by Augaton** [comment]
i will test it with the hook, thank you

**Comment by Augaton** [comment]
That's work now the legacy version of the Hdevice will be detected and inform the administrator that the legacy version is here
