### ISSUE TITLE
Not working with base, keycard, and hacking device installed

### ISSUE THREAD

**Issue by flyingkarii** [Augaton/scp-hacking-device-reloaded#6]
https://github.com/user-attachments/assets/e5cc4121-458d-4f2c-bf91-3d55c08989b4

**Comment by Augaton** [comment]
What addon do you have actually ?
And have you the old hdevice addon active ?

**Comment by flyingkarii** [comment]
Base, Keycard, and Hacking Reloaded.
No
https://steamcommunity.com/sharedfiles/filedetails/?id=3224846395

**Comment by Augaton** [comment]
There no error with the f10 console menu ?

**Comment by flyingkarii** [comment]
![image](https://github.com/user-attachments/assets/54e0a80c-1bb4-41a8-92fe-203c154fc698)
None, but someone said this!

**Comment by Augaton** [comment]
Haaa .. this is the table that's not correctly loaded so the swep don't work well

**Comment by flyingkarii** [comment]
I'll post a PR later if you don't already have a fix by then

**Comment by Augaton** [comment]
I'm not currently free to look into it and fix it for now

**Comment by Guthen** [comment]
Just for reference, this looks exactly like #2

**Comment by flyingkarii** [comment]
> Just for reference, this looks exactly like #2

Yeah, it fixes that in my PR

**Comment by flyingkarii** [comment]
Fixed by #7
